### ISSUE TITLE
No se puede avanzar después de la primera jornada en alguna ocasión.

### ISSUE THREAD

**Issue by ikersuarez01** [SpaceOddityGames/SpaceOddity#1]
Solo ha ocurrido una vez de todas las veces que he intentado reproducirlo. Al terminar la primera jornada, la primera vez que abrí el juego, terminé con una puntuación de 3/20, después aparece la pantalla en negro diciendo que has fallado la primera jornada y la siguiente pantalla que aparece es la del ipad pero sin nada escrito, como se muestra en la imagen.

**Comment by Rllona** [comment]
Solucionado.
